---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cl-operator-manager-role-corednsrewrite
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
#  resourceNames: 
#  - "coredns"
  verbs:
  - get
  - list
  - update
  - watch
